spring.application.name=springsecurityWahdi
spring.datasource.url=jdbc:postgresql://localhost:5432/springsecuritydb
spring.datasource.username=postgres
spring.datasource.password=9847123
spring.jpa.hibernate.ddl-auto=update
server.port=8089

